apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpetstore-backend-deployment
  namespace: jpetstore-dev
spec:
  selector:
    matchLabels:
      app: jpetstore
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: jpetstore
        tier: backend
    spec:
      containers:
        - name: jpetstore-backend
          image: lanznx/jpetstore:k8s.3
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_URL

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080